---
- hosts: all
  become: yes
  user: vagrant
  vars:
    mysql_user: test_user
    mysql_password: test_password
    mysql_database: test_database

  tasks:
    - name: apt install packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
        - python3
        - python3-pip
        - python3-dev
        - python3-venv
        - git
        - nginx
        - nodejs
        - npm

    - name: rename nodejs to node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link

    - name: make venv
      command: python3 -m venv /home/vagrant/env

    - name: pip install packagess
      pip: name={{ item }} state=present virtualenv=/home/vagrant/env virtualenv_python=python3.5
      with_items:
        - numpy
        - scipy
        - scikit-learn
        - bottle
        - pyMySQL3

    - name: install MySQL packages
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server
        - mysql-client
        - libmysqld-dev
        - libmysqlclient-dev
        - python-mysqldb

    - name: create mysql database
      mysql_db: name={{ mysql_database }} state=present

    - name: create mysql user
      mysql_user: name={{ mysql_user }} host={{ item }} password={{ mysql_password }} priv={{ mysql_database }}.*:ALL,GRANT state=present
      with_items:
        - localhost
        - 192.168.33.%

    - name: uncomment a line bind-address = 127.0.0.1
      replace: >
        dest=/etc/mysql/mysql.conf.d/mysqld.cnf
        regexp='^bind-address'
        replace='#bind-address'

    - name: start mysql
      service: name=mysql state=restarted enabled=yes

